### ISSUE TITLE
No output on Widget. Local weather and forecast config falls back to 'zero' days

### ISSUE THREAD

**Issue by rudma** [BasvanH/habpanel-widget-openweathermap#14]
I've had Openhab running in a vm on my mac and applied all task for importing the widget. In HABPanel I was able to run the Widget without issues.
After installing OpenHAB on a Raspberry I had no luck getting it to work again. The widget just has a blank output.
In PaperUI I can set the hrs to 96 and days to 1, but after saving the 'thing' goes to status 'unknown'. Once it is 'online' again the hrs are still set to 96 but days drop back to 'zero'.
When editing the widget I noticed on row 3 it says    ...href="/static/openweathermap/...   ; Is this path correct? I thought the correct path should be "/html/openweahtermap/....'

**Comment by BasvanH** [comment]
I think you have an issue with your [OpenWeathermap](https://www.openhab.org/addons/bindings/openweathermap/) binding, not with the widget. Please open up a ticket on the [Openhab Community](https://community.openhab.org/c/add-ons/bindings/15).

**Comment by rudma** [comment]
Thanks for your response @BasvanH .
Don't think there is anything wrong with the binding though. I can see all individual variables when using i.e. a dummy widget.
I will do some further trouble shooting.
-

Unresolved.  Widget stopped working in VM without doing any changes.
Things are online and data is pulled in so its most likely a widget issue.
