### ISSUE TITLE
Windspeed in forecast

### ISSUE THREAD

**Issue by Pezay** [BasvanH/habpanel-widget-openweathermap#15]
Is it possible to add the windspeed in forecast, not just for the current weather? Maybe as an option of display directly under the temperature.

Should be very valuable for us living close to the coastline.

**Comment by GrexAut** [comment]
wind is not provided in forecast api, only in current weather:
You can check yourself, which data will be provided from api:
Forecast:
https://api.openweathermap.org/data/2.5/forecast?lat=48.210033&lon=16.3634498&units=metric&appid=[your_api_token]

Current Weather:
https://api.openweathermap.org/data/2.5/weather?lat=48.210033&lon=16.3634498&units=metric&appid=[your_api_token]
