### ISSUE TITLE
Armbian Installation

### ISSUE THREAD

**Issue by tomnick** [BasvanH/habpanel-widget-openweathermap#16]
There is no /opt/openHAB/data/openhab/conf/html where I can install OWM. Any idea where to create under Armbian?

**Comment by GrexAut** [comment]
I installed it today, the html folder on my armbian installation is at /etc/openhab2/html

I created there a folder with openweathermap and placed the icon and images as described in the readme.md

Correct Structure: 
/etc/openhab2/html
    /openweathermap
        owm.controller.js
        /weather-icons-master
       /images
            feel.png
            humidity.png
            wind.png
