### ISSUE TITLE
Weather_OWM_ConditionId

### ISSUE THREAD

**Issue by LifeIsBrilliant** [BasvanH/habpanel-widget-openweathermap#2]
copy paste error in 
String		Weather_OWM_ConditionId			            "ConditionId [%s]"				                {channel="openweathermap:weather-and-forecast:api:Schwechat:current#time-stamp"}

should be
String		Weather_OWM_ConditionId			            "ConditionId [%s]"				                {channel="openweathermap:weather-and-forecast:api:Schwechat:current#condition-id"}

**Comment by BasvanH** [comment]
Where did you spot this? The item is correctly spelled on the [OH forum topic](https://community.openhab.org/t/openweathermap-widget-for-habpanel/65027).

**Comment by BasvanH** [comment]
I found where you are referring to, it was in the dev branch. Solved it, thanks!
