### ISSUE TITLE
Language code

### ISSUE THREAD

**Issue by HenriDeBomb** [BasvanH/habpanel-widget-openweathermap#4]
Small issue but I belive Language code for Swedish should be "se" (and not "sw", wich is Swahili).
Tested to change config in jar directly and it works, earlier I got message on faulty language code.
But it doesn´t retrive condition in correct language anyway cause of that the only thing translated is the description. Is it possible to get that info in your nice widget?

**Comment by BasvanH** [comment]
If I understand correctly, you want the widget to perform some kind of translation? If so, it's really not the right place.

The OWM API supports [Swedish](https://openweathermap.org/forecast5#format).

So if you set your language in OH to Swedish, the OWM binding should retrieve the API values in that language. If not, you should create an [issue in this github](https://github.com/openhab/openhab2-addons/issues) here.

**Comment by HenriDeBomb** [comment]
Well thanks for reply and sorry about posting wrongly, but if you read the beginning of my post so is it an issue cause of wrong language code for Swedish (you have currently ### **Sw**) and it does Only pick the key value for Description field as translation. Below from Api docs.
"Multilingual support
Description:
You can use lang parameter to get the output in your language. We support the following languages that you can use with the corresponded lang values: 
Arabic - ar, Bulgarian - bg, Catalan - ca, Czech - cz, German - de, Greek - el, English - en, Persian (Farsi) - fa, Finnish - fi, French - fr, Galician - gl, Croatian - hr, Hungarian - hu, Italian - it, Japanese - ja, Korean - kr, Latvian - la, Lithuanian - lt, Macedonian - mk, Dutch - nl, Polish - pl, Portuguese - pt, Romanian - ro, Russian - ru, **Swedish - se**, Slovak - sk, Slovenian - sl, Spanish - es, Turkish - tr, Ukrainian - ua, Vietnamese - vi, Chinese Simplified - zh_cn, Chinese Traditional - zh_tw.
**_NOTE: Translation is only applied for the "description" field._**  "

I can post this in Openhab repository if you wish.

**Comment by BasvanH** [comment]
Ok, then this is a bug in the OWM binding not interpertating the Swedish OH language selection to the correct API language parameter 'se'.

Please create [an issue here](https://github.com/openhab/openhab2-addons/issues), and refer to this one.
