### ISSUE TITLE
Add days failed

### ISSUE THREAD

**Issue by fifipil909** [BasvanH/habpanel-widget-openweathermap#8]
hi,

Sometimes, the .getDate + day failed, and add more than one days (sometimes one month)
related to here : https://stackoverflow.com/questions/563406/add-days-to-javascript-date

init today and nextDay in the for loop solve the issue 

` 
for (var day = 0; day < 4; day++) {
   today = new Date();
   nextDay = new Date();
   nextDay.setDate(today.getDate() + day);
   nextDay.setHours(12);
   var diffHours = Math.ceil(Math.abs(today.getTime() - nextDay.getTime()) / (1000 * 3600));
   setForecastItems(day, getClosest(diffHours));
 }
`

**Comment by BasvanH** [comment]
Ok nice found, could you create a pull request, I'll be more then happy to merge it.

**Comment by fifipil909** [comment]
Done
